// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared.proto
// Protobuf C++ Version: 6.31.1

#include "shared.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace tibia {
namespace protobuf {
namespace shared {

inline constexpr Coordinate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        x_{0u},
        y_{0u},
        z_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Coordinate::Coordinate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Coordinate_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CoordinateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CoordinateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CoordinateDefaultTypeInternal() {}
  union {
    Coordinate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CoordinateDefaultTypeInternal _Coordinate_default_instance_;
}  // namespace shared
}  // namespace protobuf
}  // namespace tibia
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_shared_2eproto[5];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_shared_2eproto = nullptr;
const ::uint32_t
    TableStruct_shared_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::tibia::protobuf::shared::Coordinate, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::tibia::protobuf::shared::Coordinate, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::tibia::protobuf::shared::Coordinate, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::tibia::protobuf::shared::Coordinate, _impl_.z_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::tibia::protobuf::shared::Coordinate)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::tibia::protobuf::shared::_Coordinate_default_instance_._instance,
};
const char descriptor_table_protodef_shared_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014shared.proto\022\025tibia.protobuf.shared\"-\n"
    "\nCoordinate\022\t\n\001x\030\001 \001(\r\022\t\n\001y\030\002 \001(\r\022\t\n\001z\030\003"
    " \001(\r*\224\001\n\rPLAYER_ACTION\022\026\n\022PLAYER_ACTION_"
    "NONE\020\000\022\026\n\022PLAYER_ACTION_LOOK\020\001\022\025\n\021PLAYER"
    "_ACTION_USE\020\002\022\026\n\022PLAYER_ACTION_OPEN\020\003\022$\n"
    " PLAYER_ACTION_AUTOWALK_HIGHLIGHT\020\004*\315\005\n\r"
    "ITEM_CATEGORY\022\030\n\024ITEM_CATEGORY_ARMORS\020\001\022"
    "\031\n\025ITEM_CATEGORY_AMULETS\020\002\022\027\n\023ITEM_CATEG"
    "ORY_BOOTS\020\003\022\034\n\030ITEM_CATEGORY_CONTAINERS\020"
    "\004\022\034\n\030ITEM_CATEGORY_DECORATION\020\005\022\026\n\022ITEM_"
    "CATEGORY_FOOD\020\006\022\036\n\032ITEM_CATEGORY_HELMETS"
    "_HATS\020\007\022\026\n\022ITEM_CATEGORY_LEGS\020\010\022\030\n\024ITEM_"
    "CATEGORY_OTHERS\020\t\022\031\n\025ITEM_CATEGORY_POTIO"
    "NS\020\n\022\027\n\023ITEM_CATEGORY_RINGS\020\013\022\027\n\023ITEM_CA"
    "TEGORY_RUNES\020\014\022\031\n\025ITEM_CATEGORY_SHIELDS\020"
    "\r\022\027\n\023ITEM_CATEGORY_TOOLS\020\016\022\033\n\027ITEM_CATEG"
    "ORY_VALUABLES\020\017\022\034\n\030ITEM_CATEGORY_AMMUNIT"
    "ION\020\020\022\026\n\022ITEM_CATEGORY_AXES\020\021\022\027\n\023ITEM_CA"
    "TEGORY_CLUBS\020\022\022\"\n\036ITEM_CATEGORY_DISTANCE"
    "_WEAPONS\020\023\022\030\n\024ITEM_CATEGORY_SWORDS\020\024\022\034\n\030"
    "ITEM_CATEGORY_WANDS_RODS\020\025\022!\n\035ITEM_CATEG"
    "ORY_PREMIUM_SCROLLS\020\026\022\035\n\031ITEM_CATEGORY_T"
    "IBIA_COINS\020\027\022#\n\037ITEM_CATEGORY_CREATURE_P"
    "RODUCTS\020\030\022\030\n\024ITEM_CATEGORY_QUIVER\020\031*\245\001\n\010"
    "VOCATION\022\031\n\014VOCATION_ANY\020\377\377\377\377\377\377\377\377\377\001\022\021\n\rV"
    "OCATION_NONE\020\000\022\023\n\017VOCATION_KNIGHT\020\001\022\024\n\020V"
    "OCATION_PALADIN\020\002\022\025\n\021VOCATION_SORCERER\020\003"
    "\022\022\n\016VOCATION_DRUID\020\004\022\025\n\021VOCATION_PROMOTE"
    "D\020\n*\203\001\n\023ANIMATION_LOOP_TYPE\022)\n\034ANIMATION"
    "_LOOP_TYPE_PINGPONG\020\377\377\377\377\377\377\377\377\377\001\022 \n\034ANIMAT"
    "ION_LOOP_TYPE_INFINITE\020\000\022\037\n\033ANIMATION_LO"
    "OP_TYPE_COUNTED\020\001*4\n\tHOOK_TYPE\022\023\n\017HOOK_T"
    "YPE_SOUTH\020\001\022\022\n\016HOOK_TYPE_EAST\020\002"
};
static ::absl::once_flag descriptor_table_shared_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_shared_2eproto = {
    false,
    false,
    1311,
    descriptor_table_protodef_shared_2eproto,
    "shared.proto",
    &descriptor_table_shared_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_shared_2eproto::offsets,
    file_level_enum_descriptors_shared_2eproto,
    file_level_service_descriptors_shared_2eproto,
};
namespace tibia {
namespace protobuf {
namespace shared {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PLAYER_ACTION_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_shared_2eproto);
  return file_level_enum_descriptors_shared_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PLAYER_ACTION_internal_data_[] = {
    327680u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ITEM_CATEGORY_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_shared_2eproto);
  return file_level_enum_descriptors_shared_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t ITEM_CATEGORY_internal_data_[] = {
    1638401u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL VOCATION_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_shared_2eproto);
  return file_level_enum_descriptors_shared_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t VOCATION_internal_data_[] = {
    458751u, 32u, 32u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ANIMATION_LOOP_TYPE_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_shared_2eproto);
  return file_level_enum_descriptors_shared_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t ANIMATION_LOOP_TYPE_internal_data_[] = {
    262143u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL HOOK_TYPE_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_shared_2eproto);
  return file_level_enum_descriptors_shared_2eproto[4];
}
PROTOBUF_CONSTINIT const uint32_t HOOK_TYPE_internal_data_[] = {
    131073u, 0u, };
// ===================================================================

class Coordinate::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Coordinate>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Coordinate, _impl_._has_bits_);
};

Coordinate::Coordinate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Coordinate_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tibia.protobuf.shared.Coordinate)
}
Coordinate::Coordinate(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Coordinate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Coordinate_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Coordinate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Coordinate::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::z_));
}
Coordinate::~Coordinate() {
  // @@protoc_insertion_point(destructor:tibia.protobuf.shared.Coordinate)
  SharedDtor(*this);
}
inline void Coordinate::SharedDtor(MessageLite& self) {
  Coordinate& this_ = static_cast<Coordinate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Coordinate::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Coordinate(arena);
}
constexpr auto Coordinate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Coordinate),
                                            alignof(Coordinate));
}
constexpr auto Coordinate::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Coordinate_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Coordinate::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Coordinate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Coordinate::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Coordinate>(), &Coordinate::ByteSizeLong,
              &Coordinate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Coordinate, _impl_._cached_size_),
          false,
      },
      &Coordinate::kDescriptorMethods,
      &descriptor_table_shared_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Coordinate_class_data_ =
        Coordinate::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Coordinate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Coordinate_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Coordinate_class_data_.tc_table);
  return Coordinate_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
Coordinate::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Coordinate, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Coordinate_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::tibia::protobuf::shared::Coordinate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 x = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Coordinate, _impl_.x_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Coordinate, _impl_.x_)}},
    // optional uint32 y = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Coordinate, _impl_.y_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(Coordinate, _impl_.y_)}},
    // optional uint32 z = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Coordinate, _impl_.z_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(Coordinate, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 x = 1;
    {PROTOBUF_FIELD_OFFSET(Coordinate, _impl_.x_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 y = 2;
    {PROTOBUF_FIELD_OFFSET(Coordinate, _impl_.y_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 z = 3;
    {PROTOBUF_FIELD_OFFSET(Coordinate, _impl_.z_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Coordinate::Clear() {
// @@protoc_insertion_point(message_clear_start:tibia.protobuf.shared.Coordinate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    ::memset(&_impl_.x_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.z_) -
        reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Coordinate::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Coordinate& this_ = static_cast<const Coordinate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Coordinate::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Coordinate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:tibia.protobuf.shared.Coordinate)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 x = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_x(), target);
  }

  // optional uint32 y = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_y(), target);
  }

  // optional uint32 z = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_z(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tibia.protobuf.shared.Coordinate)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Coordinate::ByteSizeLong(const MessageLite& base) {
  const Coordinate& this_ = static_cast<const Coordinate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Coordinate::ByteSizeLong() const {
  const Coordinate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:tibia.protobuf.shared.Coordinate)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // optional uint32 x = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_x());
    }
    // optional uint32 y = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_y());
    }
    // optional uint32 z = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_z());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Coordinate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Coordinate*>(&to_msg);
  auto& from = static_cast<const Coordinate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tibia.protobuf.shared.Coordinate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.x_ = from._impl_.x_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.y_ = from._impl_.y_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.z_ = from._impl_.z_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Coordinate::CopyFrom(const Coordinate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tibia.protobuf.shared.Coordinate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Coordinate::InternalSwap(Coordinate* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Coordinate, _impl_.z_)
      + sizeof(Coordinate::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Coordinate, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Coordinate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace shared
}  // namespace protobuf
}  // namespace tibia
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_shared_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
